### ISSUE TITLE
Unable to write an APB that can create OpenShift templates

### ISSUE THREAD

**Issue by eriknelson** [automationbroker/bundle-lib#118]
`CreateSandbox` creates namespaced roles for the transient namespace, and the target namespace. It doesn't provide the APB's SA privileges for creating templates in the `openshift` template. We need to come up with a way for some APBs to have privileges to perform this action.

**Comment by awels** [comment]
A use case for this is the following:

We have an APB that allows users to import a VM disk from a remote source to create VMs out of it (using kubevirt). In this APB we give the user the option to create a template instead of creating the VM. The template will contain a lot of the information most people won't care about. Then users can create instances of that VM at a later date by filling out minimal information (like name).

We had this working before by asking the user for an admin username/pw and then logging in using those credentials during the running of the ansible script. What we need is some way of asking in the apb definition to allow the apb to create templates in the openshift namespace.

**Comment by jmrodri** [comment]
Closing stale issues
